### ISSUE TITLE
preside server start datasource prompts overwriting

### ISSUE THREAD

**Issue by zspitzer** [pixl8/Preside-CMS-CommandBox-Commands#19]
when you run `preside server start` the datasource config prompts overwrite each other in the console

![image](https://github.com/pixl8/Preside-CMS-CommandBox-Commands/assets/426404/85b4bc33-54f5-44fa-a98e-3e9c8933f45f)

https://ortussolutions.atlassian.net/browse/COMMANDBOX-1596

**Comment by DominicWatson** [comment]
Reworked entirely and now working.
