### ISSUE TITLE
Using artifacts instead of downloading core from s3

### ISSUE THREAD

**Issue by cfmitrah** [pixl8/Preside-CMS-CommandBox-Commands#4]
Each time while creating a new site, it is downloading the fresh copy from preside Amazon s3 site. If the requested version was already downloaded, need to use local artifacts folder zip file

**Comment by DominicWatson** [comment]
Yes, right now it is using plain cfhttp to get the file. Really, we should be proxying to forgebox install (which will use its artifacts cache by default). There's a bit of work to be done before we get there though (refactoring how we register preside itself with forgebox, etc.).
