### ISSUE TITLE
Configurable skeleton git endpoint instead of using preside-site-skeleton.zip from _resoures folder

### ISSUE THREAD

**Issue by cfmitrah** [pixl8/Preside-CMS-CommandBox-Commands#5]
Configurable skeleton git endpoint instead of using preside-site-skeleton.zip from _resoures folder, So that pixl8/ contributors / other devs could create n number of skeletons based upon various use cases.

**Comment by DominicWatson** [comment]
That'd be neat for sure :) + we can come with a number of pre-packaged different skeletons. +10
